### ISSUE TITLE
make companies execution error

### ISSUE THREAD

**Issue by adamcysec** [eracle/linkedin#115]
After running `make companies` the following error occured:
```
scrapy_companies_1  | 2023-09-18 22:13:43 [scrapy.middleware] INFO: Enabled item pipelines:
scrapy_companies_1  | []
scrapy_companies_1  | INFO:scrapy.core.engine:Spider opened
scrapy_companies_1  | 2023-09-18 22:13:43 [scrapy.core.engine] INFO: Spider opened
scrapy_companies_1  | INFO:scrapy.extensions.logstats:Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
scrapy_companies_1  | 2023-09-18 22:13:43 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
scrapy_companies_1  | Traceback (most recent call last):
scrapy_companies_1  |   File "/usr/local/bin/scrapy", line 8, in <module>
scrapy_companies_1  |     sys.exit(execute())
scrapy_companies_1  |   File "/usr/local/lib/python3.8/site-packages/scrapy/cmdline.py", line 158, in execute
scrapy_companies_1  |     _run_print_help(parser, _run_command, cmd, args, opts)
scrapy_companies_1  |   File "/usr/local/lib/python3.8/site-packages/scrapy/cmdline.py", line 111, in _run_print_help
scrapy_companies_1  |     func(*a, **kw)
scrapy_companies_1  |   File "/usr/local/lib/python3.8/site-packages/scrapy/cmdline.py", line 166, in _run_command
scrapy_companies_1  |     cmd.run(args, opts)
scrapy_companies_1  |   File "/usr/local/lib/python3.8/site-packages/scrapy/commands/crawl.py", line 30, in run
scrapy_companies_1  |     self.crawler_process.start()
scrapy_companies_1  |   File "/usr/local/lib/python3.8/site-packages/scrapy/crawler.py", line 383, in start
scrapy_companies_1  |     install_shutdown_handlers(self._signal_shutdown)
scrapy_companies_1  |   File "/usr/local/lib/python3.8/site-packages/scrapy/utils/ossignal.py", line 19, in install_shutdown_handlers
scrapy_companies_1  |     reactor._handleSignals()
scrapy_companies_1  | AttributeError: 'EPollReactor' object has no attribute '_handleSignals'

```

Im not exactly sure what the issue is, but may be related to scrapy dependency issues - [[Error when crawl data: 'EPollReactor' object has no attribute '_handleSignals'](https://stackoverflow.com/questions/76995567/error-when-crawl-data-epollreactor-object-has-no-attribute-handlesignals)](https://stackoverflow.com/questions/76995567/error-when-crawl-data-epollreactor-object-has-no-attribute-handlesignals)

**Comment by adamcysec** [comment]
Changed the required version of scrapy to 2.11.0 and the error no longer persist.
