### ISSUE TITLE
search.py -- Exception Occurred: # extract_profile_id_from_url

### ISSUE THREAD

**Issue by py-lot** [eracle/linkedin#62]
Hi, I get errors if the profile has limited visibility.
I tried to solve it adding a way to know if the profile has limited visibility and skip it in those cases.

linkedin/spiders/search.py

```
        # Profiles out of your network have limited visibility.
        profile_out = '//*[contains(@class,"actor-name") and contains(text(),"LinkedIn Member")]'
        profile_limited_visibility = get_by_xpath_or_none(driver=driver,
                                                  xpath=profile_out,
                                                  wait_timeout=NO_RESULT_WAIT_TIMEOUT,
                                                  logs=False)

        if no_result_response is not None:
            # no results message shown: stop crawling this company
            driver.close()
            return
        else:
            users = extracts_linkedin_users(driver, api_client=self.api_client)
            for user in users:
                if profile_limited_visibility is not "LinkedIn Member":
                    if stop_criteria is not None:
                        if stop_criteria(user, stop_criteria_args):
                            # if stop criteria is matched stops the crawl, and also next pages
                            driver.close()
                            return

                    yield user
```

![image](https://user-images.githubusercontent.com/66186963/83340875-92a54c00-a2dd-11ea-88e5-3620eeaa9699.png)

this is the error:

```
Exception Occurred:
XPATH:.//*[@class="search-result__result-link ember-view"]
Error:Message:

Exception Occurred:
XPATH:.//*[@class="name actor-name"]
Error:Message:

ERROR:scrapy.core.scraper:Spider error processing <GET https://www.linkedin.com/search/results/people/?facetCurrentCompany=%5B%2211885%22%5D&page=3> (referer: https://www.linkedin.com/search/results/people/?facetCurrentCompany=%5B%2211885%22%5D&page=2)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/scrapy/utils/defer.py", line 117, in iter_errback
    yield next(it)
  File "/usr/lib/python3.8/site-packages/scrapy/utils/python.py", line 345, in __next__
    return next(self.data)
  File "/usr/lib/python3.8/site-packages/scrapy/utils/python.py", line 345, in __next__
    return next(self.data)
  File "/usr/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/lib/python3.8/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/lib/python3.8/site-packages/scrapy/spidermiddlewares/referer.py", line 338, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/lib/python3.8/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/lib/python3.8/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/app/projects/linkedin/spiders/search.py", line 55, in parser_search_results_page
    for user in users:
  File "/app/projects/linkedin/spiders/search.py", line 110, in extracts_linkedin_users
    profile_id = link.split('/')[-2]
AttributeError: 'NoneType' object has no attribute 'split'
2020-05-30 19:58:23 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.linkedin.com/search/results/people/?facetCurrentCompany=%5B%2211885%22%5D&page=3> (referer: https://www.linkedin.com/search/results/people/?facetCurrentCompany=%5B%2211885%22%5D&page=2)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/scrapy/utils/defer.py", line 117, in iter_errback
    yield next(it)
  File "/usr/lib/python3.8/site-packages/scrapy/utils/python.py", line 345, in __next__
    return next(self.data)
  File "/usr/lib/python3.8/site-packages/scrapy/utils/python.py", line 345, in __next__
    return next(self.data)
  File "/usr/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/lib/python3.8/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/lib/python3.8/site-packages/scrapy/spidermiddlewares/referer.py", line 338, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/lib/python3.8/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/lib/python3.8/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/lib/python3.8/site-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/app/projects/linkedin/spiders/search.py", line 55, in parser_search_results_page
    for user in users:
  File "/app/projects/linkedin/spiders/search.py", line 110, in extracts_linkedin_users
    profile_id = link.split('/')[-2]
AttributeError: 'NoneType' object has no attribute 'split'


```

Somebody how know fix it?
Thanks in advance,

**Comment by eracle** [comment]
Hello there, thanks for the comment.
Are you able to add an handle for fixing it?

**Comment by eracle** [comment]
if you can give me more info on how to reproduce it, like a query that I can type to find profiles with limited visibility, it would be cool

**Comment by eracle** [comment]
I recently updated the project, fixing all scraping problems occurring so far.
I am closing this.
